services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: http://backend:5555
    ports:
      - "80:80"
    networks:
      - mern-network

networks:
  mern-network:
    external: true